### ISSUE TITLE
to-do items have gone after refresh 

### ISSUE THREAD

**Issue by King-GO** [andrzejkupczyk/mantis-todolists#21] opened 2020-10-27 04:30 UTC
**Describe the bug**
to-do items not show (Things to do 0/0) after refreshing, but the items confirmed that all registered in database (mantis_plugin_todolists_tasks_table)
or add to-do items, go view issues (or somewhere) then back to issues, things to do back to 0

**To Reproduce**
1. try reinstall plugins again (manual)
2.  add to-do list
3. refresh and all items gone 

**Setting**
role: administrator 

Manage
Create and manage own tasks > developer

View
View tasks created by others > updater

**Environment (please complete the following information):**
 - MantisBT version: [e.g. 2.24.3]
 - Plugin version: [e.g. 2.1.0]
 - Database: [e.g. 10.4.10-MariaDB]
 - PHP [e.g. 7.3]

**Comment by andrzejkupczyk** [comment] 2020-10-29 17:48
I am not able to reproduce described behaviour. Please complete information about your environment.

**Comment by andrzejkupczyk** [comment] 2020-11-07 09:10
I'm closing this issue for now but it will be reopened when more details will be provided.

**Closed by andrzejkupczyk** 2020-11-07 09:10 UTC
Labels: bug, invalid
